---
- name: Get url of latest eecli release
  shell: curl --silent https://api.github.com/repos/rsanchez/eecli/releases/latest | /usr/bin/awk '/browser_download_url/ { print $2 }' | /usr/bin/sed 's/"//g'
  register: download_url
  when: not eecli_version
- name: Get url of latest eecli release
  shell: echo "https://github.com/rsanchez/eecli/releases/download/$EECLI_VERSION/craft.phar"
  environment:
    EECLI_VERSION: {{ eecli_version }}
  register: download_url
  when: eecli_version
- name: Download and install eecli to /usr/local/bin.
  get_url:
    url: {{ download_url.stdout }}
    dest: "{{ eecli_install_path }}/craft"
    mode: a+x